Comply with REUSE version 3.0 for licensing declaration.
scheme-requests-for-implementation/srfi-0 pull request #1
Opened 2023-12-06 02:04 UTC by Apteryks

2023-12-06 05:23 UTC, arthurgleckler requested changes

2023-12-06 05:23 UTC, arthurgleckler commented on srfi-0.html
> +SPDX-License-Identifier: MIT
This is not the license listed at the bottom of the document.  Note that the editors at the time hadn't yet settled on the MIT license.  The license used in this SRFI also appears in SRFIs 0, 5, 40, 44, 54, 57, 58, and 60.

2023-12-06 14:25 UTC, apteryks commented on srfi-0.html
> +SPDX-License-Identifier: MIT
Ah, I had missed that, thank you.  I've now properly licensed SRFI 0 using a custom license using SPDX's LicenseRef feature.  The license text file is extracted in LICENSES/LicenseRef-SRFI0.txt.  We should be able to reuse that strategy for the other SRFIs making use of it.

2024-01-29 19:36 UTC, arthurgleckler commented
Per the 2005 agreement, I added the Expat license.  I preserved the previous license because it promised that it would not be revoked.  I added all the SPDX declarations, too.  I'm closing this pull request because it's no longer necessary.  Thanks, though.

2024-01-29 19:36 UTC, closed without merging